### ISSUE TITLE
Failure to run

### ISSUE THREAD

**Issue by erbmur** [jezs00/pycasso#28]
Hello,
This is a wonderful project!

I am however having an issue with running it.  I have installed it per the instructions, but it seems to fail out whenever I try to run it.  Below is the systemctl status.  The only lines in the log is "pycasso has started".  I have it running on a fresh install on raspbian64 on a pi4.
![image](https://user-images.githubusercontent.com/8417776/213420062-50036da6-a18c-43fa-aa62-8b13546eb435.png)

**Comment by jezs00** [comment]
Thanks for posting.

This is probably a failure on my part to get it set up with a default image to help people on their first run. Looks like it's trying to run in external image mode at the moment. Try putting a png image of your choice in the pycasso\images\external\ folder.

I will have to make sure the program provides more meaningful feedback and handles nothing in the folder.

**Comment by erbmur** [comment]
Thanks for the quick reply.
Thank seems to have got me a little ruther, but it still seems to be failing.  Does it default to external image rather then generated?  I didn't see a seperate option to select generated?
![image](https://user-images.githubusercontent.com/8417776/213423732-86a8e960-c8ef-4fa9-ad9d-eb674e7f7ff8.png)

**Comment by jezs00** [comment]
I've not seen that error before. I wonder if it's an issue with pillow as RGBA should be a valid mode - perhaps try
`pip install pillow --upgrade`

If you have PIL installed instead of pillow that might cause a similar issue, not sure.

The program defaults on external rather than generated, the only difference between those two is external is for any image, generated is for images previously created by pycasso (easier to load with png metadata).

You can select mode here in the .config file:

```
[Providers]
###################
# Provider Weight #
###################
# Comparative chances whether any particular provider is used [integer]
# EG "external_amount = 0", "historic_amount = 1" and "stability_amount = 2" would result in:
# External images never appearing, and approximately 1 historic image appearing for every 2 stable diffusion images
external_amount = 0
historic_amount = 0
stability_amount = 0
dalle_amount = 1
```

So for example the above I'm only getting dalle images. You'll want to get this working on external images first though so you're not wasting credits when the screen doesn't work.

Thanks for trying this out. I'm a bit rusty with code

**Comment by erbmur** [comment]
Not a problem as all.  Glad to help.
Looks like its still throwing the same error.  I have tried to uninstall pil from both pip and pip3, and it wasn't present on either, and the update didn't seem to pull anything new.  I am running on the 64bit version of raspbian rather then the 32 if that could be a cause for the issue?
I won't have physical access to the pi until tonight to try it on a fresh 32bit install.

![image](https://user-images.githubusercontent.com/8417776/213428467-7c9a1932-b013-4d4b-8575-98e4c18fd0e9.png)

**Comment by jezs00** [comment]
I don't believe it should be an issue with the operating system based on
the error but I can't really think about any reason why it would be giving
that error. It's a step required for all modes so we can't just config it
out. To troubleshoot you could try editing pycasso.py and change the mode
to "RGB" instead of "RGBA"

I can try to recreate the issue on the weekend.

**Comment by erbmur** [comment]
Looks like the issue was party on my end too. I was using the PNG generated by review_screen.py in the externals folder.
Picking another one worked, with both RGB AND RGBA. Dalle worked too.
Thanks for the and sorry if I wasted your time.

"A happy fox playing the a chainsaw" was my first image.
![Screenshot_20230119-122123](https://user-images.githubusercontent.com/8417776/213442318-0a35c1d9-c1be-4b4f-a1de-a4349e790e4a.png)

**Comment by jezs00** [comment]
Glad it is working for you! Reopening as this kind of highlights a possible issue I still want to test - if an image is loaded as RGB, will it break the program? I might need to throw a situational .convert into there to avoid this issue. People should be able to use whatever image they want. I also want more resilience or at least warning when files are not found.

TODO:
Write warning for all file IO
Test loading different types of PNG into program
Check example prompt 'playing the' as it doesn't exactly work with all options
